import 'package:flutter/material.dart';

Color inactiveColor = Colors.red[300];
Color colorRed = const Color(0xffe31e27);
Color colorBlue = const Color(0xff075bd7);
Color colorInfo = const Color(0xff4ba0b5);
Color colorWarning = const Color(0xfff6c444);
Color colorDanger = const Color(0xffcb444a);
Color colorSuccess = const Color(0xff53a551);
Color colorWhite = Colors.white;
Color colorTextGrey = const Color(0xff636363);
Color oceanGreen = const Color(0xff73cea4);
Color colorGrassGreen = const Color(0xff98e05e);
Color colorLightGreen = const Color(0xff10e3ab);
Color colorPurple = const Color(0xff4c04a8);
Color colorBoldGreen = const Color(0xff36963f);
Color colorTabGreen = const Color(0xff7ee9ad);
Color colorTextBlue = const Color(0xff3f159d);
Color selectedTabGreen = const Color(0xff3b8263);
Color colorScaffoldColor = const Color(0xfffafafa);
Color colorLightGrey = Colors.grey[200];
Color colorBackgroundBlack = const Color(0xff161616);
